(defun open-project (project)
  (interactive "sProject name: ")
  (let ((pomfile (concat (getenv "WORKSPACE") "/" project "/pom.xml")))
    (if (file-exists-p pomfile)
        (find-file pomfile)
      (message (concat "Project " project " doesn't appear to exist")))))
